"""sixth Migration

Revision ID: 1760298b500f
Revises: 42fc9ed256ff
Create Date: 2019-09-21 14:59:39.943644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1760298b500f'
down_revision = '42fc9ed256ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'posted')
    # ### end Alembic commands ###
