"""seventh Migration

Revision ID: 65431eb03606
Revises: 1760298b500f
Create Date: 2019-09-21 18:39:11.686500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65431eb03606'
down_revision = '1760298b500f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('pitch', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'upvotes')
    op.drop_column('pitch', 'downvotes')
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='votes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], name='votes_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='votes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    # ### end Alembic commands ###
